#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Optional Winlogbeat setup for Cyber Sentinel XDR — User Behavior layer.

.DESCRIPTION
    NOTE: Winlogbeat is also auto-started when you click "Start Monitoring"
    in the SOC dashboard (via winlogbeat_manager.py).  This script is only
    needed for first-time configuration — to install the Windows service and
    write the initial winlogbeat.yml.  You do not need to re-run it on every
    XDR session.

    Cyber Sentinel XDR collects Windows Security events via PowerShell
    Get-WinEvent by default.  This script configures Winlogbeat as an
    OPTIONAL enhancement that provides richer field data for the user
    behavior model.

    You do NOT need to run this script.  User behavior scoring works
    out-of-the-box on any Windows machine without Winlogbeat.

    Run this script only if Winlogbeat is already installed and you want
    it to act as the event collection layer.

.PARAMETER WinlogbeatPath
    Full path to the winlogbeat.exe binary.
    Default: C:\Program Files\Elastic\Beats\winlogbeat\winlogbeat.exe

.PARAMETER LogOutputPath
    Directory where NDJSON event files are written.
    Must match the USER_LOG_DIR env var used by xdr_runtime.py.
    Default: C:\XDR_Logs

.EXAMPLE
    .\winlogbeat_setup.ps1
    .\winlogbeat_setup.ps1 -WinlogbeatPath "D:\winlogbeat\winlogbeat.exe"
    .\winlogbeat_setup.ps1 -LogOutputPath "E:\XDR_Logs"
#>

param(
    [string]$WinlogbeatPath = "C:\Program Files\Elastic\Beats\winlogbeat\winlogbeat.exe",
    [string]$LogOutputPath  = "C:\XDR_Logs"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

function Write-Step([string]$msg) {
    Write-Host "`n[STEP] $msg" -ForegroundColor Cyan
}

function Write-OK([string]$msg) {
    Write-Host "[OK]   $msg" -ForegroundColor Green
}

function Write-Warn([string]$msg) {
    Write-Host "[WARN] $msg" -ForegroundColor Yellow
}

function Write-Fail([string]$msg) {
    Write-Host "[FAIL] $msg" -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# Step 1 — Locate Winlogbeat
# ---------------------------------------------------------------------------

Write-Step "Locating Winlogbeat..."

if (-not (Test-Path $WinlogbeatPath)) {
    # Try common alternate install locations
    $candidates = @(
        "C:\winlogbeat\winlogbeat.exe",
        "C:\Program Files\winlogbeat\winlogbeat.exe",
        "D:\winlogbeat\winlogbeat.exe"
    )
    $found = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($found) {
        $WinlogbeatPath = $found
        Write-OK "Found Winlogbeat at: $WinlogbeatPath"
    } else {
        Write-Fail "Winlogbeat not found at '$WinlogbeatPath'."
        Write-Host @"

Winlogbeat is an OPTIONAL component.  Cyber Sentinel XDR user behavior
scoring already works without it via PowerShell Get-WinEvent.

To install Winlogbeat:
  1. Download from https://www.elastic.co/downloads/beats/winlogbeat
  2. Extract to C:\Program Files\Elastic\Beats\winlogbeat\
  3. Re-run this script.

Alternatively, set START_WINLOGBEAT=false in Backend\.env (the default)
and the system will use Get-WinEvent automatically.
"@ -ForegroundColor Yellow
        exit 0
    }
} else {
    Write-OK "Winlogbeat found at: $WinlogbeatPath"
}

$WinlogbeatDir = Split-Path $WinlogbeatPath -Parent

# ---------------------------------------------------------------------------
# Step 2 — Create output directory
# ---------------------------------------------------------------------------

Write-Step "Creating log output directory: $LogOutputPath"

if (-not (Test-Path $LogOutputPath)) {
    New-Item -ItemType Directory -Path $LogOutputPath -Force | Out-Null
    Write-OK "Created: $LogOutputPath"
} else {
    Write-OK "Already exists: $LogOutputPath"
}

# ---------------------------------------------------------------------------
# Step 3 — Write winlogbeat.yml
# ---------------------------------------------------------------------------

Write-Step "Writing winlogbeat.yml..."

$configPath = Join-Path $WinlogbeatDir "winlogbeat.yml"

$configContent = @"
# Cyber Sentinel XDR — Winlogbeat configuration
# Generated by winlogbeat_setup.ps1
#
# This configuration ships Windows Security events to a local NDJSON file
# so xdr_runtime.py can read them for user behavior analysis.
#
# Winlogbeat is OPTIONAL — Cyber Sentinel XDR uses PowerShell Get-WinEvent
# by default.  Enable this only if Winlogbeat is installed.

winlogbeat.event_logs:
  - name: Security
    event_id: 4624, 4625, 4634, 4647, 4648, 4663, 4670, 4672, 4688, 4776
    # Ignore machine accounts and built-in service accounts to reduce noise
    ignore_older: 4h

# Write events to local NDJSON files (no Elasticsearch required)
output.file:
  path: "$($LogOutputPath -replace '\\', '\\')"
  filename: xdr_events.ndjson
  rotate_every_kb: 102400
  number_of_files: 3

logging.level: warning
logging.to_files: true
logging.files:
  path: "$($LogOutputPath -replace '\\', '\\')"
  name: winlogbeat.log
  keepfiles: 3
"@

$configContent | Set-Content -Path $configPath -Encoding UTF8
Write-OK "Config written to: $configPath"

# ---------------------------------------------------------------------------
# Step 4 — Install / restart Winlogbeat service
# ---------------------------------------------------------------------------

Write-Step "Installing Winlogbeat as a Windows service..."

$svcName = "winlogbeat"
$svc = Get-Service -Name $svcName -ErrorAction SilentlyContinue

if ($svc) {
    Write-Warn "Winlogbeat service already installed — stopping for reconfiguration..."
    Stop-Service -Name $svcName -Force -ErrorAction SilentlyContinue
}

# Install service (idempotent — winlogbeat install-service is safe to re-run)
$installResult = & $WinlogbeatPath install-service 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Warn "install-service returned non-zero: $installResult"
}

Write-Step "Starting Winlogbeat service..."
Start-Service -Name $svcName
Start-Sleep -Seconds 3

$svc = Get-Service -Name $svcName -ErrorAction SilentlyContinue
if ($svc -and $svc.Status -eq "Running") {
    Write-OK "Winlogbeat service is running."
} else {
    Write-Fail "Winlogbeat service did not start.  Check: $LogOutputPath\winlogbeat.log"
    exit 1
}

# ---------------------------------------------------------------------------
# Step 5 — Update .env to enable Winlogbeat in the backend
# ---------------------------------------------------------------------------

Write-Step "Updating Backend .env to enable Winlogbeat..."

$envCandidates = @(
    (Join-Path (Split-Path $PSScriptRoot -Parent) ".env"),
    (Join-Path $PSScriptRoot ".env")
)
$envFile = $envCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

if ($envFile) {
    $envContent = Get-Content $envFile -Raw
    if ($envContent -match "START_WINLOGBEAT") {
        $envContent = $envContent -replace "START_WINLOGBEAT\s*=\s*\S+", "START_WINLOGBEAT=true"
        $envContent | Set-Content $envFile -Encoding UTF8 -NoNewline
        Write-OK "Updated START_WINLOGBEAT=true in: $envFile"
    } else {
        Add-Content -Path $envFile -Value "`nSTART_WINLOGBEAT=true"
        Write-OK "Added START_WINLOGBEAT=true to: $envFile"
    }

    # Also set USER_LOG_DIR if it differs from the default
    if ($LogOutputPath -ne "C:\XDR_Logs") {
        if ($envContent -match "USER_LOG_DIR") {
            $envContent = $envContent -replace "USER_LOG_DIR\s*=\s*\S+", "USER_LOG_DIR=$LogOutputPath"
            $envContent | Set-Content $envFile -Encoding UTF8 -NoNewline
        } else {
            Add-Content -Path $envFile -Value "USER_LOG_DIR=$LogOutputPath"
        }
        Write-OK "Set USER_LOG_DIR=$LogOutputPath in: $envFile"
    }
} else {
    Write-Warn "No .env file found.  Add the following lines manually:"
    Write-Host "  START_WINLOGBEAT=true" -ForegroundColor Yellow
    if ($LogOutputPath -ne "C:\XDR_Logs") {
        Write-Host "  USER_LOG_DIR=$LogOutputPath" -ForegroundColor Yellow
    }
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host "  Winlogbeat setup complete!" -ForegroundColor Green
Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host ""
Write-Host "  Winlogbeat binary : $WinlogbeatPath"
Write-Host "  Config file       : $configPath"
Write-Host "  NDJSON output     : $LogOutputPath\xdr_events.ndjson"
Write-Host ""
Write-Host "  Restart the Cyber Sentinel XDR backend to pick up the new"
Write-Host "  data source.  The user behavior log will show:"
Write-Host "    'User behavior: reading from Winlogbeat'"
Write-Host ""
Write-Host "  To revert to Get-WinEvent (the default), set:"
Write-Host "    START_WINLOGBEAT=false  in Backend\.env"
Write-Host ""
