#!/usr/bin/env python3
"""
check_payload.py — Telemetry payload diagnostic / validation script
Cyber Sentinel XDR — Endpoint Agent

PURPOSE
-------
Runs on the endpoint machine and verifies that every telemetry field the
backend expects is present and correctly typed in what the agent actually
sends.  Prints a clear PASS / FAIL / WARN report per field.

USAGE
-----
    python check_payload.py
    python check_payload.py --url http://192.168.1.100:8000 --key YOUR_API_KEY
    python check_payload.py --no-live-post

ENVIRONMENT VARIABLES (used when no CLI flags supplied)
-------------------------------------------------------
    XDR_BACKEND_URL   Backend base URL  (default: http://localhost:8000)
    XDR_API_KEY       API key           (default: changeme-dev-key)
"""

# ---------------------------------------------------------------------------
# CANONICAL FIELD LISTS
# Derived directly from the backend Pydantic models in backend.py:
#
#   class EndpointIdentity(BaseModel):   line 925
#   class EndpointTelemetry(BaseModel):  line 935
#
# Format: { "field_name": expected_python_type }
# Types map to what the backend model declares OR what the agent sends after
# the collector returns and the payload dict is assembled.
# ---------------------------------------------------------------------------

# EndpointIdentity — nested under payload["endpoint"]
CANONICAL_ENDPOINT: dict[str, type] = {
    "endpoint_id":      str,
    "hostname":         str,
    "ip_address":       str,
    "os":               str,
    "os_version":       str,
    "username":         str,
    "agent_version":    str,
    # network_interface is generated by identity.py (not in EndpointIdentity model
    # but present in the agent payload — flagged as INFO rather than FAIL)
}

# EndpointTelemetry top-level fields (excluding "endpoint" which is checked separately)
CANONICAL_TELEMETRY_TOP: dict[str, type] = {
    "timestamp":            str,    # ISO 8601 string from agent; backend auto-fills if absent
    "network":              dict,
    "system":               dict,
    "user":                 dict,
    "malware":              dict,
    "winlogbeat_events":    dict,   # agent sends {} — backend coerces [] to {}
}

# payload["network"] — from network_collector.collect_network()
# Backend reads: connections, bytes_sent, bytes_recv, suspicious_ports
# Also stored: packets_sent, packets_recv
CANONICAL_NETWORK: dict[str, type] = {
    "connections":      list,   # list of dicts; max 50
    "bytes_sent":       int,
    "bytes_recv":       int,
    "packets_sent":     int,
    "packets_recv":     int,
    "suspicious_ports": list,   # list of int
}

# Each item inside payload["network"]["connections"]
CANONICAL_NETWORK_CONN: dict[str, type] = {
    "laddr":    str,
    "raddr":    str,
    "status":   str,
    "pid":      (int, type(None)),  # pid can be None on some platforms
}

# payload["system"] — from system_collector.collect_system()
# Backend reads: cpu_percent, memory_percent, processes
CANONICAL_SYSTEM: dict[str, type] = {
    "cpu_percent":      float,
    "memory_percent":   float,
    "memory_used_mb":   float,
    "disk_percent":     float,
    "process_count":    int,
    "processes":        list,   # top 10 by CPU; list of dicts
}

# Each item inside payload["system"]["processes"]
CANONICAL_SYSTEM_PROC: dict[str, type] = {
    "pid":          (int, type(None)),
    "name":         str,
    "cpu_percent":  float,
    "memory_mb":    float,
}

# payload["user"] — from user_collector.collect_user()
# Backend UserBehaviorAgent.score_session_telemetry() reads:
#   current_user, sessions, session_count
CANONICAL_USER: dict[str, type] = {
    "current_user":     str,
    "sessions":         list,   # list of dicts
    "session_count":    int,
}

# Each item inside payload["user"]["sessions"]
CANONICAL_USER_SESSION: dict[str, type] = {
    "user":     str,
    "terminal": str,
    "host":     str,
    "started":  str,    # ISO-like string from strftime in user_collector
}

# payload["malware"] — from malware_collector.collect_malware()
# Backend MalwareAnalysisAgent.assess_process_metadata() reads:
#   suspicious, processes (full list), scanned_count
CANONICAL_MALWARE: dict[str, type] = {
    "scanned_count":    int,
    "suspicious":       list,   # list of dicts
    "processes":        list,   # full process list (name + pid)
}

# Each item inside payload["malware"]["suspicious"]
CANONICAL_MALWARE_SUSP: dict[str, type] = {
    "pid":      int,
    "name":     str,
    "path":     str,
    "reason":   str,
}

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------

import argparse
import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Path bootstrap — allow running as `python check_payload.py` from any dir
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

# ---------------------------------------------------------------------------
# Colour helpers (ANSI; auto-disabled on Windows < Win10 or when piped)
# ---------------------------------------------------------------------------

_USE_COLOUR = sys.stdout.isatty()

if _USE_COLOUR:
    _GREEN  = "\033[92m"
    _RED    = "\033[91m"
    _YELLOW = "\033[93m"
    _CYAN   = "\033[96m"
    _BOLD   = "\033[1m"
    _RESET  = "\033[0m"
else:
    _GREEN = _RED = _YELLOW = _CYAN = _BOLD = _RESET = ""


def _c(colour: str, text: str) -> str:
    return f"{colour}{text}{_RESET}"


# ---------------------------------------------------------------------------
# Report state
# ---------------------------------------------------------------------------

class _SectionResult:
    def __init__(self, name: str) -> None:
        self.name = name
        self.passed = 0
        self.failed = 0
        self.warned = 0
        self.lines: list[str] = []

    def _add(self, tag: str, colour: str, field: str, type_str: str, note: str) -> None:
        tag_str  = _c(colour, f"[{tag}]")
        self.lines.append(f"  {tag_str:<20} {field:<30} {type_str:<15} {note}")

    def ok(self, field: str, actual_type: str, note: str = "") -> None:
        self._add("PASS", _GREEN, field, actual_type, note)
        self.passed += 1

    def fail(self, field: str, note: str) -> None:
        self._add("FAIL", _RED, field, "", note)
        self.failed += 1

    def warn(self, field: str, note: str) -> None:
        self._add("WARN", _YELLOW, field, "", note)
        self.warned += 1

    def info(self, field: str, note: str) -> None:
        self._add("INFO", _CYAN, field, "", note)

    def print(self) -> None:
        total = self.passed + self.failed + self.warned
        status_colour = _GREEN if self.failed == 0 else _RED
        header = _c(_BOLD, f"=== {self.name} ===")
        print(f"\n{header}")
        for line in self.lines:
            print(line)
        summary = f"  {self.passed}/{total} fields OK"
        if self.warned:
            summary += f"  ({self.warned} warnings)"
        print(_c(status_colour, summary))

    @property
    def total(self) -> int:
        return self.passed + self.failed + self.warned


# ---------------------------------------------------------------------------
# Core checker — validates a dict against a canonical spec
# ---------------------------------------------------------------------------

def _check_dict(
    section: _SectionResult,
    data: dict,
    canonical: dict[str, type],
) -> None:
    """
    For each field in canonical: verify presence and type.
    Also flag unexpected extra keys as INFO (not failures).
    """
    for field, expected_type in canonical.items():
        if field not in data:
            section.fail(field, "MISSING")
            continue

        value = data[field]
        actual_type = type(value).__name__

        # Support union types expressed as a tuple (e.g. (int, type(None)))
        if isinstance(expected_type, tuple):
            if not isinstance(value, expected_type):
                expected_names = " | ".join(t.__name__ for t in expected_type)
                section.warn(
                    field,
                    f"expected {expected_names}, got {actual_type}",
                )
            else:
                type_display = " | ".join(t.__name__ for t in expected_type)
                section.ok(field, actual_type, f"(value: {_safe_repr(value)})")
        else:
            if not isinstance(value, expected_type):
                section.warn(
                    field,
                    f"expected {expected_type.__name__}, got {actual_type}  "
                    f"value={_safe_repr(value)}",
                )
            else:
                extra = ""
                if isinstance(value, list):
                    extra = f"({len(value)} items)"
                elif isinstance(value, dict):
                    extra = f"({len(value)} keys)"
                else:
                    extra = f"(value: {_safe_repr(value)})"
                section.ok(field, actual_type, extra)

    # Flag extra keys for awareness (not failures — backend ignores unknowns)
    extra_keys = set(data.keys()) - set(canonical.keys())
    for k in sorted(extra_keys):
        section.info(k, f"extra key not in canonical spec (value: {_safe_repr(data[k])})")


def _safe_repr(value: Any, max_len: int = 60) -> str:
    """Return a short repr, clamped to max_len characters."""
    r = repr(value)
    if len(r) > max_len:
        return r[:max_len] + "..."
    return r


# ---------------------------------------------------------------------------
# Sub-list item checking
# ---------------------------------------------------------------------------

def _check_list_items(
    section: _SectionResult,
    items: list,
    canonical: dict[str, type],
    label: str,
    max_check: int = 3,
) -> None:
    """
    Spot-check up to `max_check` items from a list against a canonical schema.
    Failures in any item bubble up to the section.
    """
    if not items:
        section.info(f"{label} items", "list is empty — item schema not verified")
        return

    check_count = min(len(items), max_check)
    bad_items: list[str] = []

    for i in range(check_count):
        item = items[i]
        if not isinstance(item, dict):
            bad_items.append(f"item[{i}] is {type(item).__name__}, expected dict")
            continue
        for field, expected_type in canonical.items():
            if field not in item:
                bad_items.append(f"item[{i}] missing '{field}'")
            else:
                v = item[field]
                if isinstance(expected_type, tuple):
                    if not isinstance(v, expected_type):
                        expected_names = " | ".join(t.__name__ for t in expected_type)
                        bad_items.append(
                            f"item[{i}]['{field}']: expected {expected_names}, "
                            f"got {type(v).__name__}"
                        )
                elif not isinstance(v, expected_type):
                    bad_items.append(
                        f"item[{i}]['{field}']: expected {expected_type.__name__}, "
                        f"got {type(v).__name__} (value={_safe_repr(v)})"
                    )

    if bad_items:
        for msg in bad_items:
            section.warn(f"{label} schema", msg)
    else:
        section.ok(
            f"{label} schema",
            "dict",
            f"(checked {check_count}/{len(items)} items — all OK)",
        )


# ---------------------------------------------------------------------------
# Validation functions per section
# ---------------------------------------------------------------------------

def validate_endpoint(identity: dict) -> _SectionResult:
    sec = _SectionResult("ENDPOINT IDENTITY  (payload['endpoint'])")
    _check_dict(sec, identity, CANONICAL_ENDPOINT)
    return sec


def validate_telemetry_top(payload: dict) -> _SectionResult:
    sec = _SectionResult("TELEMETRY TOP-LEVEL  (payload root)")
    _check_dict(sec, payload, CANONICAL_TELEMETRY_TOP)
    # Separate check: "endpoint" key must exist and be a dict
    if "endpoint" not in payload:
        sec.fail("endpoint", "MISSING — top-level identity block absent")
    elif not isinstance(payload["endpoint"], dict):
        sec.warn("endpoint", f"expected dict, got {type(payload['endpoint']).__name__}")
    else:
        sec.ok("endpoint", "dict", f"({len(payload['endpoint'])} keys)")
    return sec


def validate_network(network: dict) -> _SectionResult:
    sec = _SectionResult("NETWORK  (payload['network'])")
    _check_dict(sec, network, CANONICAL_NETWORK)
    # Spot-check connection list items
    _check_list_items(sec, network.get("connections", []), CANONICAL_NETWORK_CONN, "connections")
    # Verify suspicious_ports entries are ints
    ports = network.get("suspicious_ports", [])
    if ports:
        non_int = [p for p in ports if not isinstance(p, int)]
        if non_int:
            sec.warn("suspicious_ports items", f"non-int values found: {non_int[:5]}")
        else:
            sec.ok("suspicious_ports items", "int", f"(all {len(ports)} entries are int)")
    return sec


def validate_system(system: dict) -> _SectionResult:
    sec = _SectionResult("SYSTEM  (payload['system'])")
    _check_dict(sec, system, CANONICAL_SYSTEM)
    _check_list_items(sec, system.get("processes", []), CANONICAL_SYSTEM_PROC, "processes")
    return sec


def validate_user(user: dict) -> _SectionResult:
    sec = _SectionResult("USER  (payload['user'])")
    _check_dict(sec, user, CANONICAL_USER)
    _check_list_items(sec, user.get("sessions", []), CANONICAL_USER_SESSION, "sessions")
    return sec


def validate_malware(malware: dict) -> _SectionResult:
    sec = _SectionResult("MALWARE  (payload['malware'])")
    _check_dict(sec, malware, CANONICAL_MALWARE)
    _check_list_items(sec, malware.get("suspicious", []), CANONICAL_MALWARE_SUSP, "suspicious")
    # processes list items have a minimal schema
    _check_list_items(
        sec,
        malware.get("processes", []),
        {"pid": (int, type(None)), "name": str},
        "processes",
        max_check=3,
    )
    return sec


# ---------------------------------------------------------------------------
# Live POST test
# ---------------------------------------------------------------------------

async def _live_post_test(
    payload: dict,
    backend_url: str,
    api_key: str,
) -> None:
    """POST the assembled payload to /endpoint/ingest and report the result."""
    url = f"{backend_url.rstrip('/')}/endpoint/ingest"
    headers = {
        "X-API-Key": api_key,
        "Content-Type": "application/json",
    }

    print(_c(_BOLD, "\n=== LIVE POST TEST ==="))
    print(f"  Endpoint : {url}")
    key_display = api_key[:8] + "***" if len(api_key) > 8 else "***"
    print(f"  API Key  : {key_display}")

    try:
        import httpx
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(url, json=payload, headers=headers)

        if resp.status_code == 200:
            print(_c(_GREEN, f"  [PASS] HTTP {resp.status_code} — backend accepted the payload"))
            try:
                body = resp.json()
                print(f"         Response body: {json.dumps(body, indent=4)}")
            except Exception:
                print(f"         Response text: {resp.text[:300]}")
        else:
            print(_c(_RED, f"  [FAIL] HTTP {resp.status_code} — backend rejected the payload"))
            try:
                error_body = resp.json()
                print(f"         Error body:\n{json.dumps(error_body, indent=4)}")
            except Exception:
                print(f"         Response text: {resp.text[:500]}")

    except ImportError:
        print(_c(_YELLOW, "  [SKIP] httpx not installed — falling back to urllib"))
        await _live_post_urllib(payload, url, headers)

    except Exception as exc:
        print(_c(_RED, f"  [FAIL] Could not reach backend: {exc}"))
        print("         Is the backend running?  Check XDR_BACKEND_URL.")


async def _live_post_urllib(payload: dict, url: str, headers: dict) -> None:
    """Fallback POST using urllib (stdlib only)."""
    import urllib.request
    import urllib.error
    body_bytes = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=body_bytes, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            raw = resp.read().decode("utf-8")
            print(_c(_GREEN, f"  [PASS] HTTP {resp.status} — backend accepted the payload"))
            try:
                print(f"         Response body: {json.dumps(json.loads(raw), indent=4)}")
            except Exception:
                print(f"         Response text: {raw[:300]}")
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        print(_c(_RED, f"  [FAIL] HTTP {exc.code} — backend rejected the payload"))
        try:
            print(f"         Error body:\n{json.dumps(json.loads(raw), indent=4)}")
        except Exception:
            print(f"         Response text: {raw[:500]}")
    except Exception as exc:
        print(_c(_RED, f"  [FAIL] Could not reach backend: {exc}"))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Cyber Sentinel XDR — Telemetry payload diagnostic tool.\n"
            "Calls each collector, assembles the exact payload the agent sends,\n"
            "and verifies every field against the backend Pydantic model spec."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--url",
        default=os.environ.get("XDR_BACKEND_URL", "http://localhost:8000"),
        metavar="URL",
        help="XDR backend base URL  (env: XDR_BACKEND_URL)",
    )
    parser.add_argument(
        "--key",
        default=os.environ.get("XDR_API_KEY", "changeme-dev-key"),
        metavar="KEY",
        help="API key for X-API-Key header  (env: XDR_API_KEY)",
    )
    parser.add_argument(
        "--no-live-post",
        action="store_true",
        default=False,
        help="Skip the live POST test (schema check only)",
    )
    args = parser.parse_args()

    print(_c(_BOLD, "\nCyber Sentinel XDR — Telemetry Payload Diagnostic"))
    print("=" * 60)
    print(f"  Run time : {datetime.now(timezone.utc).isoformat()}")
    print(f"  Backend  : {args.url}")
    print(f"  Platform : {sys.platform}")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Import collectors and identity
    # ------------------------------------------------------------------
    print("\nLoading collectors...", end=" ", flush=True)
    try:
        from collectors import collect_network, collect_system, collect_user, collect_malware
        from identity import get_identity
        print(_c(_GREEN, "OK"))
    except ImportError as exc:
        print(_c(_RED, f"FAILED — {exc}"))
        print(
            "\nEnsure you are running from inside endpoint_agent/ or that\n"
            "D:\\Cyber Sentinal\\endpoint_agent is on PYTHONPATH.\n"
        )
        return 1

    # ------------------------------------------------------------------
    # 2. Collect live telemetry
    # ------------------------------------------------------------------
    print("Collecting telemetry from collectors...", end=" ", flush=True)
    try:
        network, system, user, malware = await asyncio.gather(
            collect_network(),
            collect_system(),
            collect_user(),
            collect_malware(),
        )
        print(_c(_GREEN, "OK"))
    except Exception as exc:
        print(_c(_RED, f"FAILED — {exc}"))
        return 1

    print("Loading endpoint identity...", end=" ", flush=True)
    try:
        identity = get_identity()
        print(_c(_GREEN, "OK"))
    except Exception as exc:
        print(_c(_RED, f"FAILED — {exc}"))
        return 1

    # ------------------------------------------------------------------
    # 3. Assemble payload exactly as agent.py does
    # ------------------------------------------------------------------
    payload: dict = {
        "endpoint":           identity,
        "timestamp":          datetime.now(timezone.utc).isoformat(),
        "network":            network,
        "system":             system,
        "user":               user,
        "malware":            malware,
        "winlogbeat_events":  {},
    }

    # ------------------------------------------------------------------
    # 4. Validate each section
    # ------------------------------------------------------------------
    sections = [
        validate_telemetry_top(payload),
        validate_endpoint(identity),
        validate_network(network),
        validate_system(system),
        validate_user(user),
        validate_malware(malware),
    ]

    for sec in sections:
        sec.print()

    # ------------------------------------------------------------------
    # 5. Overall summary
    # ------------------------------------------------------------------
    total_passed = sum(s.passed for s in sections)
    total_failed = sum(s.failed for s in sections)
    total_warned = sum(s.warned for s in sections)
    total_fields = sum(s.total  for s in sections)

    print("\n" + "=" * 60)
    print(_c(_BOLD, "OVERALL SUMMARY"))
    print("=" * 60)

    ok_colour  = _GREEN if total_failed == 0 else _RED
    print(_c(ok_colour, f"  {total_passed}/{total_fields} fields OK"))
    if total_failed:
        print(_c(_RED,    f"  {total_failed} FAILED  — these fields are missing or wrong type"))
    if total_warned:
        print(_c(_YELLOW, f"  {total_warned} WARNINGS — type mismatch or extra fields; "
                          "backend may still accept them via coercion"))

    if total_failed == 0 and total_warned == 0:
        print(_c(_GREEN, "\n  All canonical fields present and correctly typed."))
        print(  "  The payload should be accepted by the backend without errors.")
    elif total_failed == 0:
        print(_c(_YELLOW, "\n  No hard failures; warnings may be harmless (backend coerces many types)."))
    else:
        print(_c(_RED, "\n  Fix FAILED fields before deploying — they will cause 422 errors."))

    # ------------------------------------------------------------------
    # 6. Pretty-print raw payload (optional, for manual inspection)
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print(_c(_BOLD, "RAW PAYLOAD SNAPSHOT"))
    print("=" * 60)
    # Truncate long lists to keep output readable
    def _trim(obj: Any, list_max: int = 3) -> Any:
        if isinstance(obj, list):
            trimmed = [_trim(i, list_max) for i in obj[:list_max]]
            if len(obj) > list_max:
                trimmed.append(f"... ({len(obj) - list_max} more items)")
            return trimmed
        if isinstance(obj, dict):
            return {k: _trim(v, list_max) for k, v in obj.items()}
        return obj

    snapshot = _trim(payload)
    print(json.dumps(snapshot, indent=2, default=str))

    # ------------------------------------------------------------------
    # 7. Live POST test
    # ------------------------------------------------------------------
    if not args.no_live_post:
        await _live_post_test(payload, args.url, args.key)
    else:
        print(_c(_CYAN, "\n  [SKIP] Live POST test disabled via --no-live-post"))

    print()
    return 0 if total_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
