# install_service.ps1 — Run as Administrator
# Installs Cyber Sentinel XDR Endpoint Agent as a Windows Task Scheduler task.
#
# Usage:
#   .\install_service.ps1
#   .\install_service.ps1 -BackendUrl "http://192.168.1.100:8000" -ApiKey "prod-key-here"
#   .\install_service.ps1 -PythonPath "C:\Python312\python.exe"

param(
    [string]$BackendUrl  = "http://localhost:8000",
    [string]$ApiKey      = "changeme-dev-key",
    [string]$AgentDir    = $PSScriptRoot,
    [string]$PythonPath  = "python",
    [int]   $HealthPort  = 8765
)

#Requires -RunAsAdministrator

$TaskName   = "CyberSentinelXDR-EndpointAgent"
$AgentScript = Join-Path $AgentDir "agent.py"
$LogFile     = Join-Path $AgentDir "agent.log"
$EnvScript   = Join-Path $AgentDir "agent_env.ps1"

# ------------------------------------------------------------------
# Validate python path
# ------------------------------------------------------------------
$PythonResolved = (Get-Command $PythonPath -ErrorAction SilentlyContinue)?.Source
if (-not $PythonResolved) {
    # Try common install locations
    $Candidates = @(
        "C:\Python312\python.exe",
        "C:\Python311\python.exe",
        "C:\Python310\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
    )
    foreach ($c in $Candidates) {
        if (Test-Path $c) { $PythonResolved = $c; break }
    }
}
if (-not $PythonResolved) {
    $PythonResolved = $PythonPath   # fall back to whatever the user supplied
}
Write-Host "Python interpreter : $PythonResolved"

# ------------------------------------------------------------------
# Remove existing task if present
# ------------------------------------------------------------------
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

# ------------------------------------------------------------------
# Write the env-wrapper script that sets variables then launches agent
# ------------------------------------------------------------------
@"
# agent_env.ps1 — auto-generated by install_service.ps1
# Do NOT edit manually — re-run install_service.ps1 to update.

`$env:XDR_BACKEND_URL        = '$BackendUrl'
`$env:XDR_API_KEY            = '$ApiKey'
`$env:XDR_AGENT_HEALTH_PORT  = '$HealthPort'

& '$PythonResolved' '$AgentScript' *>> '$LogFile'
"@ | Out-File -FilePath $EnvScript -Encoding utf8

Write-Host "Env wrapper written : $EnvScript"

# ------------------------------------------------------------------
# Task Scheduler components
# ------------------------------------------------------------------
$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -WindowStyle Hidden -File `"$EnvScript`"" `
    -WorkingDirectory $AgentDir

# Trigger: run at system startup (no login required)
$Trigger = New-ScheduledTaskTrigger -AtStartup

# Settings: restart on failure (up to 10 times, 1 min apart), no time limit
$Settings = New-ScheduledTaskSettingsSet `
    -RestartCount 10 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -MultipleInstances IgnoreNew `
    -StartWhenAvailable

# Principal: SYSTEM account with highest privileges so netsh/taskkill succeed
$Principal = New-ScheduledTaskPrincipal `
    -UserId "SYSTEM" `
    -LogonType ServiceAccount `
    -RunLevel Highest

# ------------------------------------------------------------------
# Register and start
# ------------------------------------------------------------------
Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Principal $Principal `
    -Description "Cyber Sentinel XDR Endpoint Agent — telemetry collection and SOAR command executor" `
    -Force | Out-Null

Write-Host "Task '$TaskName' registered successfully."
Write-Host "Starting task now..."

Start-ScheduledTask -TaskName $TaskName

# Give the process a moment to start and confirm
Start-Sleep -Seconds 2
$State = (Get-ScheduledTask -TaskName $TaskName).State
Write-Host "Task state : $State"
Write-Host ""
Write-Host "Agent log  : $LogFile"
Write-Host "Health URL : http://localhost:$HealthPort/health"
Write-Host ""
Write-Host "Done. Use .\uninstall_service.ps1 to remove."
