; ============================================================================
;  Cyber Sentinel XDR — Windows Installer (Inno Setup 6)
;
;  Produces a single Setup .exe that:
;    - shows a EULA the user must accept,
;    - asks the user to choose a role: SERVER or ENDPOINT,
;    - (Endpoint) collects the backend URL + API key,
;    - installs CyberSentinelAgent.exe,
;    - registers a background auto-start task that runs the agent as SYSTEM,
;    - upgrades cleanly in place (same AppId) and uninstalls fully.
;
;  BUILD:
;    1. Install Inno Setup 6  (https://jrsoftware.org/isdl.php)
;    2. Make sure packaging\dist\CyberSentinelAgent.exe exists
;       (run packaging\build_agent.ps1 first).
;    3. Open this file in Inno Setup and click Build,  OR run:
;         "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" CyberSentinelXDR.iss
;    Output: packaging\dist\CyberSentinelXDR-Setup-<version>.exe
; ============================================================================

#define MyAppName    "Cyber Sentinel XDR"
#define MyAppVersion "1.0.0"
#define MyPublisher  "Cyber Sentinel XDR"
#define AgentExe     "CyberSentinelAgent.exe"
#define TaskName     "CyberSentinelXDR Endpoint Agent"

; Flip to 1 once the SERVER package (backend.exe + dashboard + models) is built
; and its [Files] entries are added below. While 0, the Server role is disabled.
#define ServerBundled 0

[Setup]
; AppId MUST stay constant across versions so new installers upgrade in place
; (and preserve config) instead of creating a second copy.
AppId={{8F3A1C7E-2B4D-4E9A-9C1F-7A6B5D4E3C2A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyPublisher}
DefaultDirName={autopf}\Cyber Sentinel XDR
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Active response + service install require elevation.
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
LicenseFile=EULA.txt
WizardStyle=modern
Compression=lzma2/max
SolidCompression=yes
OutputDir=..\dist
OutputBaseFilename=CyberSentinelXDR-Setup-{#MyAppVersion}
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#AgentExe}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; --- ENDPOINT role -----------------------------------------------------------
Source: "..\dist\{#AgentExe}"; DestDir: "{app}"; Flags: ignoreversion; Check: IsEndpoint
Source: "EULA.txt";           DestDir: "{app}"; Flags: ignoreversion

; --- SERVER role (add when backend.exe / dashboard / models are built) --------
#if ServerBundled == 1
; Source: "..\dist\server\backend.exe";  DestDir: "{app}\server"; Flags: ignoreversion recursesubdirs; Check: IsServer
; Source: "..\dist\server\dashboard\*";  DestDir: "{app}\server\dashboard"; Flags: ignoreversion recursesubdirs; Check: IsServer
; Source: "..\dist\server\models\*";     DestDir: "{app}\server\models";    Flags: ignoreversion recursesubdirs; Check: IsServer
#endif

[UninstallDelete]
; run_agent.cmd is generated by [Code] at install time, so remove it explicitly.
Type: files; Name: "{app}\run_agent.cmd"

[Code]
var
  RolePage: TInputOptionWizardPage;
  EndpointPage: TInputQueryWizardPage;

{ 0 = Server, 1 = Endpoint }
function IsEndpoint: Boolean;
begin
  Result := (RolePage <> nil) and (RolePage.SelectedValueIndex = 1);
end;

function IsServer: Boolean;
begin
  Result := (RolePage <> nil) and (RolePage.SelectedValueIndex = 0);
end;

procedure InitializeWizard;
begin
  { Role selection — exclusive radio options, shown right after the EULA. }
  RolePage := CreateInputOptionPage(wpLicense,
    'Installation Type',
    'Which Cyber Sentinel XDR component are you installing on this machine?',
    'Choose one, then click Next.',
    True,   { Exclusive = radio behavior }
    False); { ListBox = False -> radio buttons }
  RolePage.Add('Server  —  the SOC dashboard + detection engine (install on ONE central machine)');
  RolePage.Add('Endpoint  —  the lightweight monitoring agent (install on each PC you want to watch)');
  RolePage.SelectedValueIndex := 1;  { default: Endpoint }

  { Endpoint configuration — where is the server, and the shared API key. }
  EndpointPage := CreateInputQueryPage(RolePage.ID,
    'Endpoint Configuration',
    'Point this agent at your Cyber Sentinel XDR server',
    'The agent sends telemetry to this server and receives response commands from it.');
  EndpointPage.Add('Backend server URL (e.g. http://192.168.1.5:8001):', False);
  EndpointPage.Add('API key (must match XDR_API_KEY in the server''s .env):', False);
  EndpointPage.Values[0] := 'http://192.168.1.5:8001';
  EndpointPage.Values[1] := '';
end;

{ Skip the endpoint-config page when the Server role is selected. }
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if (PageID = EndpointPage.ID) and IsServer then
    Result := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  if (CurPageID = RolePage.ID) and IsServer then
  begin
#if ServerBundled == 0
    MsgBox('The Server package is being finalised and is not included in this build yet.'#13#10#13#10 +
           'Please choose "Endpoint" to install the monitoring agent.',
           mbInformation, MB_OK);
    Result := False;
#endif
  end;

  if (CurPageID = EndpointPage.ID) then
  begin
    if Trim(EndpointPage.Values[0]) = '' then
    begin
      MsgBox('Please enter the backend server URL (e.g. http://192.168.1.5:8001).', mbError, MB_OK);
      Result := False;
    end;
  end;
end;

{ Stop any running/previous agent so its .exe is not locked during upgrade. }
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  rc: Integer;
begin
  Result := '';
  Exec(ExpandConstant('{sys}\schtasks.exe'), '/end /tn "{#TaskName}"', '', SW_HIDE, ewWaitUntilTerminated, rc);
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/f /im {#AgentExe}', '', SW_HIDE, ewWaitUntilTerminated, rc);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Exe, Url, Key, Cmd, CmdFile, Params: String;
  rc: Integer;
begin
  if (CurStep = ssPostInstall) and IsEndpoint then
  begin
    Exe := ExpandConstant('{app}\{#AgentExe}');
    Url := Trim(EndpointPage.Values[0]);
    Key := Trim(EndpointPage.Values[1]);

    { Write a tiny launcher .cmd so the scheduled task avoids nested-quote issues.
      The API key lives in this file inside Program Files (admin-only writable). }
    Cmd := '@echo off' + #13#10 + '"' + Exe + '" --backend-url "' + Url + '"';
    if Key <> '' then
      Cmd := Cmd + ' --api-key "' + Key + '"';
    Cmd := Cmd + #13#10;

    CmdFile := ExpandConstant('{app}\run_agent.cmd');
    SaveStringToFile(CmdFile, Cmd, False);

    { Register a startup task that runs the agent as SYSTEM (full privileges for
      SOAR actions) every time the machine boots, then start it immediately.
      The action is launched via `cmd /c "..."` so the spaces in the Program
      Files path are handled correctly — pointing the task straight at the .cmd
      fails with 0x80070002 (file not found) because Task Scheduler splits the
      unquoted path on its first space. }
    Params := '/create /tn "{#TaskName}" /sc onstart /ru SYSTEM /rl HIGHEST /f /tr "cmd /c \"' + CmdFile + '\""';
    Exec(ExpandConstant('{sys}\schtasks.exe'), Params, '', SW_HIDE, ewWaitUntilTerminated, rc);
    Exec(ExpandConstant('{sys}\schtasks.exe'), '/run /tn "{#TaskName}"', '', SW_HIDE, ewWaitUntilTerminated, rc);

    if rc <> 0 then
      MsgBox('The agent was installed but the background task could not be started automatically.'#13#10 +
             'You can start it manually by running run_agent.cmd in the install folder, as Administrator.',
             mbInformation, MB_OK);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  rc: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    { Stop and remove the background task, then kill any running agent. }
    Exec(ExpandConstant('{sys}\schtasks.exe'), '/end /tn "{#TaskName}"', '', SW_HIDE, ewWaitUntilTerminated, rc);
    Exec(ExpandConstant('{sys}\schtasks.exe'), '/delete /tn "{#TaskName}" /f', '', SW_HIDE, ewWaitUntilTerminated, rc);
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/f /im {#AgentExe}', '', SW_HIDE, ewWaitUntilTerminated, rc);
    { Note: C:\ProgramData\CyberSentinel (endpoint identity + quarantine) is left
      in place on purpose so a reinstall keeps the same endpoint_id. Delete it
      manually for a completely clean removal. }
  end;
end;
